# options for analysis running
run:
  skip-dirs:
    - .*~
  skip-files:
    - ".*\\.my\\.go$"
    - _test.go

linters:
  disable-all: true
  enable:
    - gosimple
    - staticcheck
    - stylecheck
    - unused
  fast: false
